name: legacy-auto-compile
trigger:
  type: file_save
  pattern: "legacy/**/*.{cbl,f,pas,bas}"
action:
  type: command
  command: "bash -c 'if [[ $KIRO_FILE_PATH == *.cbl ]]; then cobc -x -o ${KIRO_FILE_PATH%.cbl} $KIRO_FILE_PATH; elif [[ $KIRO_FILE_PATH == *.f ]]; then gfortran -o ${KIRO_FILE_PATH%.f} $KIRO_FILE_PATH; elif [[ $KIRO_FILE_PATH == *.pas ]]; then fpc -o${KIRO_FILE_PATH%.pas} $KIRO_FILE_PATH; elif [[ $KIRO_FILE_PATH == *.bas ]]; then fbc -o ${KIRO_FILE_PATH%.bas} $KIRO_FILE_PATH; fi'"
  message: "👻 Ancient Spirit Rebound to Binary - Multi-Language Resurrection Complete."
