/**
 * ═══════════════════════════════════════════════════════════
 * BASIC BRIDGE TEMPLATE
 * ═══════════════════════════════════════════════════════════
 * 
 * GENERATED BY @necro-bridge/core
 * CUSTOMIZE THIS TEMPLATE FOR YOUR BASIC PROGRAM
 */

const LegacyBridge = require('./LegacyBridge');

class BasicBridge extends LegacyBridge {
  constructor() {
    super({
      name: 'BASIC',
      year: 1983,
      binary: 'your-basic-binary',  // CHANGE THIS
      description: 'BASIC CALCULATION',
      params: ['param1', 'param2', 'param3']  // CHANGE THIS
    });
  }
  
  /**
   * PARSE BASIC OUTPUT
   * CUSTOMIZE THIS METHOD BASED ON YOUR PROGRAM'S OUTPUT FORMAT
   * 
   * BASIC TYPICALLY USES PRINT STATEMENTS
   * EXAMPLE OUTPUT: "RESULT: 1234.56"
   */
  parseOutput(stdout) {
    // DEFAULT PATTERN: "RESULT: " FOLLOWED BY NUMBER
    const resultPattern = /RESULT:\s*(\d+\.?\d*)/;
    const match = stdout.match(resultPattern);
    
    if (!match) {
      return {
        success: false,
        result: null,
        error: 'BASIC OUTPUT DOES NOT MATCH EXPECTED FORMAT'
      };
    }
    
    const result = parseFloat(match[1]);
    
    return {
      success: true,
      result: result,
      error: null
    };
  }
}

module.exports = BasicBridge;
