/**
 * ═══════════════════════════════════════════════════════════
 * COBOL BRIDGE TEMPLATE
 * ═══════════════════════════════════════════════════════════
 * 
 * GENERATED BY @necro-bridge/core
 * CUSTOMIZE THIS TEMPLATE FOR YOUR COBOL PROGRAM
 * 
 * USAGE:
 * 1. UPDATE THE CONFIGURATION IN constructor()
 * 2. CUSTOMIZE parseOutput() TO MATCH YOUR PROGRAM'S OUTPUT FORMAT
 * 3. OPTIONALLY OVERRIDE getBinaryPath() OR buildCommand()
 * 4. RUN: node cobol-server.js (SEE BOTTOM OF FILE)
 */

const LegacyBridge = require('./LegacyBridge');
const path = require('path');

class CobolBridge extends LegacyBridge {
  constructor() {
    super({
      name: 'COBOL',
      year: 1959,
      binary: 'your-cobol-binary',  // ⚠️ CHANGE THIS TO YOUR BINARY NAME
      description: 'COBOL CALCULATION',
      params: ['param1', 'param2', 'param3']  // ⚠️ CHANGE THIS TO YOUR PARAMETERS
    });
  }
  
  /**
   * PARSE COBOL OUTPUT
   * ⚠️ CUSTOMIZE THIS METHOD BASED ON YOUR PROGRAM'S OUTPUT FORMAT
   * 
   * EXAMPLE OUTPUT FORMATS:
   * - "RESULT: 1234.56"
   * - "OUTPUT: 1234.56"
   * - "TOTAL: 1234.56"
   * - "MONTHLY PAYMENT: 1234.56"
   * 
   * @param {string} stdout - STANDARD OUTPUT FROM COBOL BINARY
   * @returns {Object} { success: boolean, result: number|null, error: string|null }
   */
  parseOutput(stdout) {
    // DEFAULT PATTERN: "RESULT: XXXX.XX"
    // ⚠️ MODIFY THIS REGEX TO MATCH YOUR OUTPUT FORMAT
    const resultPattern = /RESULT:\s*(\d+\.\d{2})/;
    const match = stdout.match(resultPattern);
    
    if (!match) {
      return {
        success: false,
        result: null,
        error: 'COBOL OUTPUT DOES NOT MATCH EXPECTED FORMAT "RESULT: XXXX.XX"'
      };
    }
    
    const result = parseFloat(match[1]);
    
    return {
      success: true,
      result: result,
      error: null
    };
  }
  
  /**
   * OPTIONAL: OVERRIDE getBinaryPath() IF YOUR BINARY IS IN A CUSTOM LOCATION
   * DEFAULT LOCATION: ./legacy/cobol/<binary-name>
   */
  // getBinaryPath() {
  //   return path.join(__dirname, 'legacy', 'cobol', this.binary);
  // }
  
  /**
   * OPTIONAL: OVERRIDE buildCommand() FOR CUSTOM PARAMETER FORMATTING
   * DEFAULT FORMAT: <binary> <param1> <param2> <param3>
   */
  // buildCommand(params) {
  //   const binaryPath = this.getBinaryPath();
  //   // CUSTOM FORMATTING EXAMPLE:
  //   return `${binaryPath} --param1=${params.param1} --param2=${params.param2}`;
  // }
}

module.exports = CobolBridge;

// ═══════════════════════════════════════════════════════════
// STANDALONE EXPRESS SERVER (OPTIONAL)
// ═══════════════════════════════════════════════════════════
// UNCOMMENT THE CODE BELOW TO RUN THIS AS A STANDALONE SERVER
// RUN: node cobol-bridge.js
// ═══════════════════════════════════════════════════════════

/*
const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3001;

// MIDDLEWARE
app.use(cors());
app.use(express.json());

// INSTANTIATE BRIDGE
const bridge = new CobolBridge();

// HEALTH CHECK ENDPOINT
app.get('/api/health', (req, res) => {
  res.json({ 
    status: 'OPERATIONAL',
    language: bridge.name,
    year: bridge.year,
    description: bridge.description,
    parameters: bridge.params
  });
});

// CALCULATION ENDPOINT
app.post('/api/calculate', async (req, res) => {
  try {
    const result = await bridge.execute(req.body);
    res.json(result);
  } catch (error) {
    const statusCode = error.error === 'INVALID INPUT' ? 400 : 500;
    res.status(statusCode).json(error);
  }
});

// START SERVER
app.listen(PORT, () => {
  console.log(`👻 ${bridge.name} BRIDGE SERVER LISTENING ON PORT ${PORT}`);
  console.log(`📋 PARAMETERS: ${bridge.params.join(', ')}`);
  console.log(`🔌 ENDPOINTS:`);
  console.log(`   GET  /api/health`);
  console.log(`   POST /api/calculate`);
});
*/
