/**
 * ═══════════════════════════════════════════════════════════
 * COBOL BRIDGE TEMPLATE
 * ═══════════════════════════════════════════════════════════
 * 
 * GENERATED BY @necro-bridge/core
 * CUSTOMIZE THIS TEMPLATE FOR YOUR COBOL PROGRAM
 */

const LegacyBridge = require('./LegacyBridge');

class CobolBridge extends LegacyBridge {
  constructor() {
    super({
      name: 'COBOL',
      year: 1959,
      binary: 'your-cobol-binary',  // CHANGE THIS
      description: 'COBOL CALCULATION',
      params: ['param1', 'param2', 'param3']  // CHANGE THIS
    });
  }
  
  /**
   * PARSE COBOL OUTPUT
   * CUSTOMIZE THIS METHOD BASED ON YOUR PROGRAM'S OUTPUT FORMAT
   * 
   * EXAMPLE OUTPUT FORMATS:
   * - "RESULT: 1234.56"
   * - "OUTPUT: 1234.56"
   * - "TOTAL: 1234.56"
   */
  parseOutput(stdout) {
    // DEFAULT PATTERN: "RESULT: XXXX.XX"
    const resultPattern = /RESULT:\s*(\d+\.\d{2})/;
    const match = stdout.match(resultPattern);
    
    if (!match) {
      return {
        success: false,
        result: null,
        error: 'COBOL OUTPUT DOES NOT MATCH EXPECTED FORMAT "RESULT: XXXX.XX"'
      };
    }
    
    const result = parseFloat(match[1]);
    
    return {
      success: true,
      result: result,
      error: null
    };
  }
  
  /**
   * OPTIONAL: OVERRIDE getBinaryPath() IF YOUR BINARY IS IN A CUSTOM LOCATION
   */
  // getBinaryPath() {
  //   return '/custom/path/to/your-cobol-binary';
  // }
  
  /**
   * OPTIONAL: OVERRIDE buildCommand() FOR CUSTOM PARAMETER FORMATTING
   */
  // buildCommand(params) {
  //   const binaryPath = this.getBinaryPath();
  //   // CUSTOM FORMATTING EXAMPLE:
  //   return `${binaryPath} --param1=${params.param1} --param2=${params.param2}`;
  // }
}

module.exports = CobolBridge;
