/**
 * ═══════════════════════════════════════════════════════════
 * FORTRAN BRIDGE TEMPLATE
 * ═══════════════════════════════════════════════════════════
 * 
 * GENERATED BY @necro-bridge/core
 * CUSTOMIZE THIS TEMPLATE FOR YOUR FORTRAN PROGRAM
 */

const LegacyBridge = require('./LegacyBridge');

class FortranBridge extends LegacyBridge {
  constructor() {
    super({
      name: 'FORTRAN',
      year: 1957,
      binary: 'your-fortran-binary',  // CHANGE THIS
      description: 'FORTRAN CALCULATION',
      params: ['param1', 'param2', 'param3']  // CHANGE THIS
    });
  }
  
  /**
   * PARSE FORTRAN OUTPUT
   * CUSTOMIZE THIS METHOD BASED ON YOUR PROGRAM'S OUTPUT FORMAT
   * 
   * FORTRAN TYPICALLY USES WRITE(*,*) OR PRINT* STATEMENTS
   * EXAMPLE OUTPUT: "RESULT:  1234.56"
   */
  parseOutput(stdout) {
    // DEFAULT PATTERN: "RESULT: " FOLLOWED BY NUMBER
    const resultPattern = /RESULT:\s*(\d+\.?\d*)/;
    const match = stdout.match(resultPattern);
    
    if (!match) {
      return {
        success: false,
        result: null,
        error: 'FORTRAN OUTPUT DOES NOT MATCH EXPECTED FORMAT'
      };
    }
    
    const result = parseFloat(match[1]);
    
    return {
      success: true,
      result: result,
      error: null
    };
  }
}

module.exports = FortranBridge;
