/**
 * ═══════════════════════════════════════════════════════════
 * FORTRAN BRIDGE TEMPLATE
 * ═══════════════════════════════════════════════════════════
 * 
 * GENERATED BY @necro-bridge/core
 * CUSTOMIZE THIS TEMPLATE FOR YOUR FORTRAN PROGRAM
 * 
 * USAGE:
 * 1. UPDATE THE CONFIGURATION IN constructor()
 * 2. CUSTOMIZE parseOutput() TO MATCH YOUR PROGRAM'S OUTPUT FORMAT
 * 3. OPTIONALLY OVERRIDE getBinaryPath() OR buildCommand()
 * 4. RUN: node fortran-server.js (SEE BOTTOM OF FILE)
 */

const LegacyBridge = require('./LegacyBridge');
const path = require('path');

class FortranBridge extends LegacyBridge {
  constructor() {
    super({
      name: 'FORTRAN',
      year: 1957,
      binary: 'your-fortran-binary',  // ⚠️ CHANGE THIS TO YOUR BINARY NAME
      description: 'FORTRAN CALCULATION',
      params: ['param1', 'param2', 'param3']  // ⚠️ CHANGE THIS TO YOUR PARAMETERS
    });
  }
  
  /**
   * PARSE FORTRAN OUTPUT
   * ⚠️ CUSTOMIZE THIS METHOD BASED ON YOUR PROGRAM'S OUTPUT FORMAT
   * 
   * FORTRAN TYPICALLY USES WRITE(*,*) OR PRINT* STATEMENTS
   * EXAMPLE OUTPUT FORMATS:
   * - "RESULT:  1234.56"
   * - "RANGE: 5678.90"
   * - "TRAJECTORY: 1234.5678"
   * 
   * NOTE: FORTRAN MAY INCLUDE EXTRA WHITESPACE IN OUTPUT
   * 
   * @param {string} stdout - STANDARD OUTPUT FROM FORTRAN BINARY
   * @returns {Object} { success: boolean, result: number|null, error: string|null }
   */
  parseOutput(stdout) {
    // DEFAULT PATTERN: "RESULT: " FOLLOWED BY NUMBER (FLEXIBLE DECIMAL PLACES)
    // ⚠️ MODIFY THIS REGEX TO MATCH YOUR OUTPUT FORMAT
    const resultPattern = /RESULT:\s*([\d.]+)/;
    const match = stdout.match(resultPattern);
    
    if (!match) {
      return {
        success: false,
        result: null,
        error: 'FORTRAN OUTPUT DOES NOT MATCH EXPECTED FORMAT "RESULT: <number>"'
      };
    }
    
    const result = parseFloat(match[1]);
    
    // VALIDATE RESULT IS A VALID NUMBER
    if (isNaN(result)) {
      return {
        success: false,
        result: null,
        error: 'FORTRAN OUTPUT CONTAINS INVALID NUMERIC VALUE'
      };
    }
    
    return {
      success: true,
      result: result,
      error: null
    };
  }
  
  /**
   * OPTIONAL: OVERRIDE getBinaryPath() IF YOUR BINARY IS IN A CUSTOM LOCATION
   * DEFAULT LOCATION: ./legacy/fortran/<binary-name>
   */
  // getBinaryPath() {
  //   return path.join(__dirname, 'legacy', 'fortran', this.binary);
  // }
}

module.exports = FortranBridge;

// ═══════════════════════════════════════════════════════════
// STANDALONE EXPRESS SERVER (OPTIONAL)
// ═══════════════════════════════════════════════════════════
// UNCOMMENT THE CODE BELOW TO RUN THIS AS A STANDALONE SERVER
// RUN: node fortran-bridge.js
// ═══════════════════════════════════════════════════════════

/*
const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3002;

// MIDDLEWARE
app.use(cors());
app.use(express.json());

// INSTANTIATE BRIDGE
const bridge = new FortranBridge();

// HEALTH CHECK ENDPOINT
app.get('/api/health', (req, res) => {
  res.json({ 
    status: 'OPERATIONAL',
    language: bridge.name,
    year: bridge.year,
    description: bridge.description,
    parameters: bridge.params
  });
});

// CALCULATION ENDPOINT
app.post('/api/calculate', async (req, res) => {
  try {
    const result = await bridge.execute(req.body);
    res.json(result);
  } catch (error) {
    const statusCode = error.error === 'INVALID INPUT' ? 400 : 500;
    res.status(statusCode).json(error);
  }
});

// START SERVER
app.listen(PORT, () => {
  console.log(`👻 ${bridge.name} BRIDGE SERVER LISTENING ON PORT ${PORT}`);
  console.log(`📋 PARAMETERS: ${bridge.params.join(', ')}`);
  console.log(`🔌 ENDPOINTS:`);
  console.log(`   GET  /api/health`);
  console.log(`   POST /api/calculate`);
});
*/
