/**
 * ═══════════════════════════════════════════════════════════
 * PASCAL BRIDGE TEMPLATE
 * ═══════════════════════════════════════════════════════════
 * 
 * GENERATED BY @necro-bridge/core
 * CUSTOMIZE THIS TEMPLATE FOR YOUR PASCAL PROGRAM
 */

const LegacyBridge = require('./LegacyBridge');

class PascalBridge extends LegacyBridge {
  constructor() {
    super({
      name: 'PASCAL',
      year: 1970,
      binary: 'your-pascal-binary',  // CHANGE THIS
      description: 'PASCAL CALCULATION',
      params: ['param1', 'param2', 'param3']  // CHANGE THIS
    });
  }
  
  /**
   * PARSE PASCAL OUTPUT
   * CUSTOMIZE THIS METHOD BASED ON YOUR PROGRAM'S OUTPUT FORMAT
   * 
   * PASCAL TYPICALLY USES WRITELN() STATEMENTS
   * EXAMPLE OUTPUT: "RESULT: 1234.56"
   */
  parseOutput(stdout) {
    // DEFAULT PATTERN: "RESULT: " FOLLOWED BY NUMBER
    const resultPattern = /RESULT:\s*(\d+\.?\d*)/;
    const match = stdout.match(resultPattern);
    
    if (!match) {
      return {
        success: false,
        result: null,
        error: 'PASCAL OUTPUT DOES NOT MATCH EXPECTED FORMAT'
      };
    }
    
    const result = parseFloat(match[1]);
    
    return {
      success: true,
      result: result,
      error: null
    };
  }
}

module.exports = PascalBridge;
