/**
 * ═══════════════════════════════════════════════════════════
 * UNIVERSAL BRIDGE SERVER TEMPLATE
 * ═══════════════════════════════════════════════════════════
 * 
 * GENERATED BY @necro-bridge/core
 * 
 * STANDARDIZED EXPRESS.JS API WRAPPER FOR LEGACY BINARIES
 * SUPPORTS MULTIPLE LEGACY LANGUAGES THROUGH BRIDGE PATTERN
 * 
 * USAGE:
 * 1. CUSTOMIZE THE BRIDGES ARRAY BELOW WITH YOUR BRIDGE CLASSES
 * 2. ENSURE ALL BRIDGE FILES ARE IN THE SAME DIRECTORY
 * 3. RUN: node universal-server.js
 * 4. TEST: curl -X POST http://localhost:3001/api/calculate/cobol -H "Content-Type: application/json" -d '{"param1": 100, "param2": 5, "param3": 30}'
 */

const express = require('express');
const cors = require('cors');

// ═══════════════════════════════════════════════════════════
// CONFIGURATION
// ═══════════════════════════════════════════════════════════

const PORT = process.env.PORT || 3001;

// ⚠️ IMPORT YOUR BRIDGE CLASSES HERE
// UNCOMMENT AND MODIFY BASED ON YOUR BRIDGES
const CobolBridge = require('./cobol-bridge');
// const FortranBridge = require('./fortran-bridge');
// const PascalBridge = require('./pascal-bridge');
// const BasicBridge = require('./basic-bridge');

// ⚠️ REGISTER YOUR BRIDGES HERE
const bridges = {
  cobol: new CobolBridge(),
  // fortran: new FortranBridge(),
  // pascal: new PascalBridge(),
  // basic: new BasicBridge()
};

// ═══════════════════════════════════════════════════════════
// EXPRESS APP SETUP
// ═══════════════════════════════════════════════════════════

const app = express();

// MIDDLEWARE
app.use(cors());
app.use(express.json());

// REQUEST LOGGING MIDDLEWARE
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
  next();
});

// ═══════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════

/**
 * GET BRIDGE BY LANGUAGE IDENTIFIER
 */
function getBridge(language) {
  const languageKey = language.toLowerCase();
  
  if (!bridges[languageKey]) {
    throw new Error(`UNSUPPORTED LANGUAGE: ${language}`);
  }
  
  return bridges[languageKey];
}

/**
 * GET LIST OF SUPPORTED LANGUAGES
 */
function getSupportedLanguages() {
  return Object.keys(bridges);
}

/**
 * GET METADATA FOR ALL BRIDGES
 */
function getLanguageMetadata() {
  return Object.entries(bridges).map(([id, bridge]) => ({
    id: id,
    name: bridge.name,
    year: bridge.year,
    description: bridge.description,
    parameters: bridge.params
  }));
}

// ═══════════════════════════════════════════════════════════
// API ENDPOINTS
// ═══════════════════════════════════════════════════════════

/**
 * HEALTH CHECK ENDPOINT
 * GET /api/health
 */
app.get('/api/health', (req, res) => {
  res.json({ 
    status: 'OPERATIONAL', 
    message: 'UNIVERSAL BRIDGE SERVER ONLINE - READY TO SUMMON ANCIENT SPIRITS',
    timestamp: new Date().toISOString(),
    supported_languages: getSupportedLanguages()
  });
});

/**
 * LIST AVAILABLE LANGUAGES ENDPOINT
 * GET /api/languages
 */
app.get('/api/languages', (req, res) => {
  const languages = getLanguageMetadata();
  
  res.json({
    count: languages.length,
    languages: languages
  });
});

/**
 * UNIVERSAL CALCULATION ENDPOINT
 * POST /api/calculate/:language
 * 
 * EXAMPLE REQUEST:
 * POST /api/calculate/cobol
 * {
 *   "param1": 200000,
 *   "param2": 5.5,
 *   "param3": 30
 * }
 */
app.post('/api/calculate/:language', async (req, res) => {
  const { language } = req.params;
  const params = req.body;
  
  try {
    // GET BRIDGE FOR SPECIFIED LANGUAGE
    const bridge = getBridge(language);
    
    // EXECUTE CALCULATION
    const result = await bridge.execute(params);
    
    // RETURN SUCCESSFUL RESPONSE
    res.json(result);
  } catch (error) {
    // DETERMINE STATUS CODE
    const statusCode = error.error === 'INVALID INPUT' ? 400 : 500;
    
    // RETURN ERROR RESPONSE
    res.status(statusCode).json({
      error: error.error || 'CORE DUMP DETECTED',
      details: error.details || error.message,
      language: language,
      supported_languages: getSupportedLanguages()
    });
  }
});

/**
 * DEFAULT CALCULATION ENDPOINT (FIRST REGISTERED LANGUAGE)
 * POST /api/calculate
 */
app.post('/api/calculate', async (req, res) => {
  const params = req.body;
  
  // USE FIRST REGISTERED LANGUAGE AS DEFAULT
  const defaultLanguage = getSupportedLanguages()[0];
  
  try {
    const bridge = getBridge(defaultLanguage);
    const result = await bridge.execute(params);
    
    res.json(result);
  } catch (error) {
    const statusCode = error.error === 'INVALID INPUT' ? 400 : 500;
    res.status(statusCode).json({
      error: error.error || 'CORE DUMP DETECTED',
      details: error.details || error.message
    });
  }
});

// ═══════════════════════════════════════════════════════════
// ERROR HANDLING MIDDLEWARE
// ═══════════════════════════════════════════════════════════

app.use((err, req, res, next) => {
  console.error('[ERROR]', err);
  
  res.status(500).json({
    error: 'INTERNAL SERVER ERROR',
    details: err.message
  });
});

// ═══════════════════════════════════════════════════════════
// START SERVER
// ═══════════════════════════════════════════════════════════

app.listen(PORT, () => {
  console.log('═══════════════════════════════════════════════════════');
  console.log('👻 UNIVERSAL NECRO-BRIDGE SERVER');
  console.log('═══════════════════════════════════════════════════════');
  console.log(`🔌 LISTENING ON PORT ${PORT}`);
  console.log('📡 CORS ENABLED');
  console.log('⚡ READY TO RESURRECT ANCIENT SPIRITS:');
  
  getLanguageMetadata().forEach(lang => {
    console.log(`   • ${lang.name} (${lang.year}) - ${lang.description}`);
  });
  
  console.log('═══════════════════════════════════════════════════════');
  console.log('🔌 ENDPOINTS:');
  console.log(`   GET  http://localhost:${PORT}/api/health`);
  console.log(`   GET  http://localhost:${PORT}/api/languages`);
  console.log(`   POST http://localhost:${PORT}/api/calculate/:language`);
  console.log(`   POST http://localhost:${PORT}/api/calculate (default)`);
  console.log('═══════════════════════════════════════════════════════');
});
